spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #the next line is writen when we a json object
      #value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
server:
  port: 8081